services:
  app:
    build: .
    container_name: calmwave_api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017 # Acessível pelo nome do serviço Docker 'mongo'
      - SECRET_KEY=calmwavesecret
      - DENOISE_SERVICE_URL=http://10.67.57.148:8000/audio/denoise # <--- PONTO CRÍTICO: URL do serviço de Denoising
      - SECRET_KEY=calmwavesecret # Considere mover para um .env file ou secrets do Docker
      - DENOISE_SERVER=http://10.67.57.148:8000/audio/denoise # <--- CORRIGIDO: Nome da variável para corresponder à config.py
      - BASE_URL=http://10.67.57.147:5000 # <--- RENOMEADO: Agora BASE_URL para consistência com o código Flask
      - UPLOAD_FOLDER=/app/uploads       # Adicionado para ser explicitamente configurado
      - TEMP_WAV_FOLDER=/app/temp_wavs   # Adicionado para ser explicitamente configurado
      - PROCESSED_FOLDER=/app/processed  # Adicionado para ser explicitamente configurado
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      # Não adicionamos um volume para ./temp_wavs, pois são arquivos temporários
      # e geralmente não precisamos persistí-los no host. Eles serão criados
      # e limpos dentro do contêiner pelo AudioProcessor.
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: calmwave_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data: