services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./temp_wavs:/app/temp_wavs
      - ./logs:/app/logs
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - SECRET_KEY=dev-secret-key
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DATABASE=calmwave
      - DENOISE_SERVER=http://10.67.57.148:8000
      - DENOISE_TIMEOUT=300
      - BASE_URL=http://localhost:5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: