/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Register/index`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Register/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../services/api`; params?: Router.UnknownInputParams; } | { pathname: `/../routes/index`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Home/index`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../App`; params?: Router.UnknownInputParams; } | { pathname: `/../types/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/Register/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/Register/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/../routes/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/Home/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/Home/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../App`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../screens/Register/index${`?${string}` | `#${string}` | ''}` | `/../screens/Register/styles${`?${string}` | `#${string}` | ''}` | `/../services/api${`?${string}` | `#${string}` | ''}` | `/../routes/index${`?${string}` | `#${string}` | ''}` | `/../screens/Home/index${`?${string}` | `#${string}` | ''}` | `/../screens/Home/styles${`?${string}` | `#${string}` | ''}` | `/../App${`?${string}` | `#${string}` | ''}` | `/../types/navigation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Register/index`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Register/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../services/api`; params?: Router.UnknownInputParams; } | { pathname: `/../routes/index`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Home/index`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/Home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../App`; params?: Router.UnknownInputParams; } | { pathname: `/../types/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
