
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#111111",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  topContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
    marginTop: 50,
  },
  title: {
    fontFamily: "Azonix",
    fontSize: 28,
    color: "#FFFFFF",
    marginBottom: 10,
  },
  subtitle: {
    fontFamily: "BigShoulders-Regular",
    fontSize: 24,
    color: "#9EBDC1",
    marginBottom: 20,
  },
  recordContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 120,
  },
  recordButton: {
    backgroundColor: "#5319C6",
    borderRadius: 10,
    padding: 10,
    width: "50%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  recordButtonText: {
    color: "#fff",
    textAlign: "center",
    fontSize: 28,
    fontFamily: "BigShoulders-Regular",
  },
  recordButtonIcon: {
    width: 16,
    height: 21,
  },
  waveformContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 60,
    backgroundColor: "#222",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#5319C6",
    width: 350,
    marginTop: 60,
  },
  waveformBar: {
    width: 6,
    marginHorizontal: 2,
    backgroundColor: "#fff",
    borderRadius: 10,
  },
  stopButton: {
    marginTop: 100,
  },
  stopButtonOuter: {
    width: 60,
    height: 60,
    backgroundColor: "#391C73",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  stopButtonInner: {
    width: 45,
    height: 45,
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  stopButtonSquad: {
    width: 15,
    height: 15,
    backgroundColor: "#391C73",
    borderRadius: 2,
  },
  timerText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    marginTop: 10,
  },
  processingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  processingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#000',
  },
  errorText: {
    color: '#ff0000',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
  uploadingText: {
    color: '#5319C6',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
  connectionText: {
    color: '#9EBDC1',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
  successText: {
    color: '#4CAF50',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
});
