/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Usuarios;
import javax.swing.JOptionPane;
import Models.Conexao;
import java.math.BigInteger;



/**
 *
 * @author fatec-dsm2
 */
public class FMenu extends javax.swing.JFrame {

    /**
     * Creates new form FLogin
     */
   
    
    public FMenu() {
      
        initComponents();
    }
    
    Conexao conexaoDB = new Conexao();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sair = new javax.swing.JPanel();
        Imagem_Fundo = new javax.swing.JPanel();
        img_fundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_cadusu = new javax.swing.JLabel();
        btn_albuns = new javax.swing.JLabel();
        img_fone = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        btn_ruidos = new javax.swing.JLabel();
        lbl_introdução = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_sair.setOpaque(false);
        btn_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_sairLayout = new javax.swing.GroupLayout(btn_sair);
        btn_sair.setLayout(btn_sairLayout);
        btn_sairLayout.setHorizontalGroup(
            btn_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        btn_sairLayout.setVerticalGroup(
            btn_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        img_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/menu/nav_menu.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        btn_cadusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/menu/btn_usu.png"))); // NOI18N
        btn_cadusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadusuMouseClicked(evt);
            }
        });

        btn_albuns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/menu/btn_albuns.png"))); // NOI18N
        btn_albuns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_albunsMouseClicked(evt);
            }
        });

        img_fone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/menu/fone_menu.png"))); // NOI18N

        lbl_nome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(21, 21, 21));
        lbl_nome.setText("Placeholder");
        lbl_nome.setRequestFocusEnabled(false);

        btn_ruidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/menu/btn_ruidos.png"))); // NOI18N
        btn_ruidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ruidosMouseClicked(evt);
            }
        });

        lbl_introdução.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_introdução.setForeground(new java.awt.Color(21, 21, 21));
        lbl_introdução.setText("Bem vindo, ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_albuns)
                    .addComponent(btn_cadusu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(img_fone)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ruidos)
                        .addGap(131, 131, 131))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_introdução)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(lbl_introdução, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_albuns)
                    .addComponent(btn_ruidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cadusu)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(img_fone)
                        .addGap(106, 106, 106))))
        );

        javax.swing.GroupLayout Imagem_FundoLayout = new javax.swing.GroupLayout(Imagem_Fundo);
        Imagem_Fundo.setLayout(Imagem_FundoLayout);
        Imagem_FundoLayout.setHorizontalGroup(
            Imagem_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Imagem_FundoLayout.createSequentialGroup()
                .addGroup(Imagem_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Imagem_FundoLayout.setVerticalGroup(
            Imagem_FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Imagem_FundoLayout.createSequentialGroup()
                .addComponent(img_fundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 656, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagem_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(963, 963, 963)
                    .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagem_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1431, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1022, 777));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_sairMouseClicked

    private void btn_cadusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadusuMouseClicked
        // TODO add your handling code here:
        FCreateUser createuser = new FCreateUser();
        
        createuser.user = lbl_nome.getText();
        createuser.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btn_cadusuMouseClicked

    private void btn_ruidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ruidosMouseClicked
        // TODO add your handling code here:
        FRuidos rui = new FRuidos();
        
        rui.user = lbl_nome.getText();
        rui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruidosMouseClicked

    private void btn_albunsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_albunsMouseClicked
        // TODO add your handling code here:
        FPlaylist play = new FPlaylist();
        
        
        play.user = lbl_nome.getText();
        play.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_albunsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }
        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Imagem_Fundo;
    private javax.swing.JLabel btn_albuns;
    private javax.swing.JLabel btn_cadusu;
    private javax.swing.JLabel btn_ruidos;
    private javax.swing.JPanel btn_sair;
    private javax.swing.JLabel img_fone;
    private javax.swing.JLabel img_fundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_introdução;
    public javax.swing.JLabel lbl_nome;
    // End of variables declaration//GEN-END:variables
}
