services:
  app:
    build: .
    container_name: calmwave_api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017 # Acessível pelo nome do serviço Docker 'mongo'
      - SECRET_KEY=calmwavesecret
      - DENOISE_SERVICE_URL=http://10.67.57.148:8000/audio/denoise # <--- PONTO CRÍTICO: URL do serviço de Denoising
      - API_BASE_URL_FOR_FRONTEND=http://10.67.57.147:5000 # <--- NOVO: Base URL que o frontend deve usar para o Flask
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: calmwave_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data: